### ISSUE TITLE
Measurement parameter issues

### ISSUE THREAD

**Issue by Tyrdall** [fraunhofer-isi/micat-vue#27]
**Energy savings** don't have a parameter ID. Hence we cannot use it: 
![image](https://github.com/fraunhofer-isi/micat-vue/assets/536181/b22c5bdb-7710-45f4-873b-d2269c4d0ebb)

Secondly, Annual renovation rate comes without values: 
![image](https://github.com/fraunhofer-isi/micat-vue/assets/536181/6bc7529d-8f7d-4066-9260-086d9b304fee)

**Comment by fhg-isi** [comment]
The energy savings are no parameter but specified by the users.
