### ISSUE TITLE
Deactivate renovatebot for micat vue

### ISSUE THREAD

**Issue by fhg-isi** [fraunhofer-isi/micat-vue#34]
Currently renovate might be triggered by other repositories because it is installed as app on the
level of github.com/fraunhofer-isi:
https://github.com/organizations/fraunhofer-isi/settings/installations/40132388

=> Adapt workflow and disable it for micat-vue.

**Comment by fhg-isi** [comment]
I asked renovate to provide an option to exlude individual repositories:

https://github.com/renovatebot/renovate/discussions/28618

For the time beeing, I manualle selected all repositories but micat-vue:

![image](https://github.com/fraunhofer-isi/micat-vue/assets/76424482/10d22234-c977-4cad-a9c0-4a5c4829a95e)

**Comment by fhg-isi** [comment]
@Tyrdall 

FYI: Its also possible to set explicit versions for some of the dependencies in the renovate config file:
https://github.com/fraunhofer-isi/micat-vue/blob/main/renovate-config.js

Also see 
https://github.com/fraunhofer-isi/micat-next/blob/main/renovate-config.js
for some examples related to eslint.

**Comment by Tyrdall** [comment]
@fhg-isi I had set the `enabled` option, but it has no effect.

**Comment by fhg-isi** [comment]
Thanks. Good to know. Then we keep the individual selection on organization level for the time beeing. 

Updated link to GitHub Discussion:
https://github.com/orgs/community/discussions/120980
